apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admin-panel-metrics-pvc
  namespace: flink
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3