################################################################################
# Unified RBAC for Flink Namespace
################################################################################

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink
  namespace: flink

---
# Internal Flink Role: Permissions for Flink to manage its own infrastructure
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-internal-role
  namespace: flink
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/finalizers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-internal-binding
  namespace: flink
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink-internal-role
subjects:
  - kind: ServiceAccount
    name: flink
    namespace: flink

---
# External Access Role: Consolidates "event-reader" and "creator" for the Admin Panel
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-panel-flink-access
  namespace: flink
rules:
  - apiGroups: ["", "events.k8s.io"]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["flink.apache.org"]
    resources: ["flinkdeployments"]
    verbs: ["get", "list", "watch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-panel-flink-binding
  namespace: flink
subjects:
  - kind: ServiceAccount
    name: default
    namespace: flink
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin-panel-flink-access

---
# Operator Role: Allows the default SA in the flink namespace to manage Flink CRDs
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-operator-role
  namespace: flink
rules:
  - apiGroups: ["flink.apache.org"]
    resources: ["flinkdeployments", "flinksessionjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-operator-binding
  namespace: flink
subjects:
  - kind: ServiceAccount
    name: default
    namespace: flink
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink-operator-role
